import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto((process.env.PLANNER_TEST_URL||'http://127.0.0.1:3211')+'/trip-planner?destination=Bangkok');await page.waitForSelector('.calendar-day');await page.locator('#origin-search').fill('Yangon');
 await page.evaluate(()=>{document.querySelector('#start-date').value='2026-12-01';document.querySelector('#end-date').value='2026-12-15';document.querySelector('#trip-planner-form').dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#studio-next').click();await page.locator('#passport-country').fill('Myanmar');await page.locator('#studio-next').click();await page.locator('#budget').fill('30000');await page.locator('[data-step-button="4"]').click();
 const input=page.locator('#global-place-search');await input.fill('Hua Hin Beach');await page.locator('#global-place-results button').first().click();await page.locator('.place-search-preview').waitFor();assert.match(await page.locator('.place-search-preview').innerText(),/DAY TRIP/);await page.locator('.place-search-preview').getByRole('button',{name:'+ Add to Trip',exact:true}).click();assert.equal(await page.locator('.searched-place-row').count(),1);assert.equal(await page.getByRole('button',{name:'✓ Added to Trip',exact:true}).isDisabled(),true);
 await page.locator('.searched-place-row').getByRole('button',{name:'Choose Day / Set Priority'}).click();const row=page.locator('.preference-place').first();await row.locator('summary').click();await row.getByRole('combobox',{name:/Preferred day/}).selectOption('5');await row.getByRole('combobox',{name:/How important/}).selectOption('must_visit');
 await page.reload();await page.waitForSelector('.searched-place-row',{state:'attached'});const prefs=JSON.parse(await page.locator('#itinerary-preferences-state').inputValue());assert.equal(prefs.activityPreferences[0].preferredDay,5);assert.equal(prefs.activityPreferences[0].priority,'must_visit');
 await page.locator('[data-step-button="4"]').click();await input.fill('Eiffel Tower Paris');await page.locator('#global-place-results button').first().click();await page.locator('.place-search-preview').getByRole('button',{name:'+ Add to Trip',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Cancel'}).click();assert.equal(await page.locator('.searched-place-row').count(),1);await page.locator('.place-search-preview').getByRole('button',{name:'+ Add to Trip',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Add Anyway'}).click();await page.waitForFunction(()=>document.querySelectorAll('.searched-place-row').length===2);
 await page.screenshot({path:'/tmp/packswift-place-search.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS: live autocomplete/details, day trip, duplicate prevention, day/priority reload, distance cancel/confirm, mobile.');
}finally{await browser.close();}
