CREATE TABLE IF NOT EXISTS planner_activities (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  city_id VARCHAR(32) NOT NULL,
  city_name VARCHAR(120) NOT NULL,
  slug VARCHAR(160) NOT NULL,
  title VARCHAR(180) NOT NULL,
  category VARCHAR(80) NOT NULL,
  description VARCHAR(600) NOT NULL,
  cost_usd DECIMAL(10, 2) NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  image_alt VARCHAR(255) NOT NULL,
  image_credit VARCHAR(255) NULL,
  image_source_url VARCHAR(500) NULL,
  suitable_groups JSON NOT NULL,
  purpose_tags JSON NOT NULL,
  budget_tier ENUM('budget', 'mid', 'luxury') NOT NULL,
  pace_level ENUM('slow', 'balanced', 'fast') NOT NULL,
  experience_tags JSON NOT NULL,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_planner_activity_city_slug (city_id, slug),
  INDEX idx_planner_activity_filter (city_id, budget_tier, pace_level, is_active)
);
