export const hostedPackSwiftSchema = {
  users: `CREATE TABLE IF NOT EXISTS hosted_users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    platform_email TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  savedTrips: `CREATE TABLE IF NOT EXISTS hosted_saved_trips (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    plan_id TEXT NOT NULL,
    destination TEXT NOT NULL,
    travel_month TEXT NOT NULL,
    budget REAL NOT NULL,
    trip_data TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES hosted_users(id) ON DELETE CASCADE,
    UNIQUE (user_id, plan_id)
  )`,
  tripSessions: `CREATE TABLE IF NOT EXISTS hosted_trip_sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    public_id TEXT NOT NULL UNIQUE,
    user_id INTEGER NOT NULL,
    trip_data TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'planned',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES hosted_users(id) ON DELETE CASCADE
  )`,
  tripItineraryItems: `CREATE TABLE IF NOT EXISTS hosted_trip_itinerary_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trip_session_id INTEGER NOT NULL,
    provider TEXT NOT NULL DEFAULT 'packswift_catalog',
    place_id TEXT NOT NULL,
    position INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (trip_session_id) REFERENCES hosted_trip_sessions(id) ON DELETE CASCADE,
    UNIQUE (trip_session_id, provider, place_id)
  )`,
  aiRateLimits: `CREATE TABLE IF NOT EXISTS hosted_ai_rate_limits (
    requester_hash TEXT NOT NULL,
    window_bucket INTEGER NOT NULL,
    request_count INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (requester_hash, window_bucket)
  )`,
  readiness: `CREATE TABLE IF NOT EXISTS hosted_readiness_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trip_session_id INTEGER NOT NULL,
    item_key TEXT NOT NULL,
    category TEXT NOT NULL,
    item_name TEXT NOT NULL,
    description TEXT NOT NULL,
    assistant_type TEXT NOT NULL DEFAULT 'manual',
    is_required INTEGER NOT NULL DEFAULT 1,
    is_completed INTEGER NOT NULL DEFAULT 0,
    completion_source TEXT,
    confirmation_reference TEXT,
    completed_at TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (trip_session_id) REFERENCES hosted_trip_sessions(id) ON DELETE CASCADE,
    UNIQUE (trip_session_id, item_key)
  )`,
  packing: `CREATE TABLE IF NOT EXISTS hosted_packing_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trip_session_id INTEGER NOT NULL,
    category TEXT NOT NULL,
    item_name TEXT NOT NULL,
    is_completed INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (trip_session_id) REFERENCES hosted_trip_sessions(id) ON DELETE CASCADE,
    UNIQUE (trip_session_id, category, item_name)
  )`,
  destinationPlaces: `CREATE TABLE IF NOT EXISTS destination_places_cache (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    provider TEXT NOT NULL DEFAULT 'google_places',
    provider_place_id TEXT NOT NULL,
    destination_key TEXT NOT NULL,
    destination_name TEXT NOT NULL,
    destination_scope TEXT NOT NULL,
    country_name TEXT,
    request_category TEXT NOT NULL,
    search_query TEXT NOT NULL,
    category_tags TEXT NOT NULL,
    first_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider, provider_place_id, destination_key)
  )`,
  itineraryActivities: `CREATE TABLE IF NOT EXISTS hosted_itinerary_activities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trip_session_id INTEGER NOT NULL,
    day_number INTEGER NOT NULL,
    sequence_number INTEGER NOT NULL,
    time_period TEXT NOT NULL,
    start_time TEXT,
    end_time TEXT,
    place_name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    thumbnail_url TEXT,
    duration_minutes INTEGER NOT NULL DEFAULT 60,
    estimated_cost REAL NOT NULL DEFAULT 0,
    cost_currency TEXT NOT NULL DEFAULT 'USD',
    transit_mode TEXT,
    transit_minutes INTEGER,
    transit_distance_km REAL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (trip_session_id) REFERENCES hosted_trip_sessions(id) ON DELETE CASCADE,
    UNIQUE (trip_session_id, day_number, sequence_number)
  )`,
  visaRules: `CREATE TABLE IF NOT EXISTS hosted_visa_rules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    origin_country_code TEXT NOT NULL,
    destination_country_code TEXT NOT NULL,
    status TEXT NOT NULL,
    allowed_days INTEGER,
    summary TEXT NOT NULL,
    official_portal_url TEXT,
    source_note TEXT,
    checked_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (origin_country_code, destination_country_code)
  )`,
} as const;
